name: deeplearning_ai_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - tensorflow
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - public-tests
      - autils
      - deeplearning-mplstyle
      - assignment-utils
